# Generated by Django 5.2 on 2025-05-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_document_file_type_alter_document_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='last_active',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='memory_key_points',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
