# Generated by Django 5.2 on 2025-05-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0004_chatsession_last_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='processing_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
